flowchart TD
  A[INICIO] --> B{MENU}

  B --> C
  B --> L
  B --> R
  B --> Z[FIM]

  C[PROCESSO OPCAO 1 CRIAR UTILIZADOR] --> C1[/INPUT USERNAME/]
  C1 --> C2[/INPUT PASSWORD E CONFIRMACAO/]
  C2 --> C3[PROCESSO VALIDAR PASSWORD]
  C3 --> C4[PROCESSO GERAR SALT]
  C4 --> C5[PROCESSO HASH PBKDF2]
  C5 --> C6[/OUTPUT GUARDAR EM USERS JSON/]
  C6 --> B

  L[PROCESSO OPCAO 2 LOGIN] --> L1[/INPUT USERNAME IP PASSWORD/]
  L1 --> L2[PROCESSO LER BLACKLIST JSON]
  L2 --> D1{DECISAO IP BLOQUEADO}

  D1 -->|SIM| X1[/OUTPUT RECUSAR ACESSO/]
  X1 --> X2[/OUTPUT REGISTAR LOG CSV/]
  X2 --> B

  D1 -->|NAO| L3[PROCESSO LER USERS JSON]
  L3 --> D2{DECISAO UTILIZADOR EXISTE}

  D2 -->|NAO| Y1[/OUTPUT ERRO UTILIZADOR NAO EXISTE/]
  Y1 --> Y2[/OUTPUT REGISTAR LOG CSV/]
  Y2 --> B

  D2 -->|SIM| L4[PROCESSO VERIFICAR LOCKOUT]
  L4 --> D3{DECISAO CONTA BLOQUEADA}

  D3 -->|SIM| W1[/OUTPUT LOCKOUT ATIVO/]
  W1 --> W2[/OUTPUT REGISTAR LOG CSV/]
  W2 --> B

  D3 -->|NAO| L5[PROCESSO VERIFICAR PASSWORD]
  L5 --> D4{DECISAO CREDENCIAIS OK}

  D4 -->|SIM| S1[PROCESSO RESET FALHAS E LOCK]  /*limpar qualquer penalização anterior associada à conta*/
  S1 --> S2[/OUTPUT GUARDAR USERS JSON/]
  S2 --> S3[/OUTPUT REGISTAR LOG CSV/]
  S3 --> S4[PROCESSO ANALISAR LOGS E ATUALIZAR BLACKLIST]
  S4 --> B

  D4 -->|NAO| F1[PROCESSO INCREMENTAR FALHAS]
  F1 --> F2[PROCESSO BACKOFF LOCKOUT SE NECESSARIO]
  F2 --> F3[/OUTPUT GUARDAR USERS JSON/]
  F3 --> F4[/OUTPUT REGISTAR LOG CSV/]
  F4 --> F5[PROCESSO ANALISAR LOGS E ATUALIZAR BLACKLIST]
  F5 --> B

  R[PROCESSO OPCAO 3 ANALISAR LOGS E GERAR BLACKLIST] --> R1[PROCESSO LER LOGS CSV]
  R1 --> D5{DECISAO LOGS EXISTEM}

  D5 -->|NAO| R2[/OUTPUT AVISO SEM LOGS/]
  R2 --> B

  D5 -->|SIM| R3[PROCESSO CONVERTER LINHAS EM LOGENTRY]
  R3 --> R4[PROCESSO ANALISAR FALHAS POR IP]
  R4 --> D6{DECISAO HA IPS SUSPEITOS}

  D6 -->|NAO| R5[/OUTPUT RELATORIO SEM NOVOS BLOQUEIOS/]
  R5 --> B

  D6 -->|SIM| R6[PROCESSO GERAR BLOQUEIOS]
  R6 --> R7[/OUTPUT GUARDAR BLACKLIST JSON/]
  R7 --> R8[/OUTPUT MOSTRAR RELATORIO NO CONSOLE/]
  R8 --> B
